"""Add pluspunkte and gewichtung columns

Revision ID: b00a438c48bd
Revises: 
Create Date: 2025-01-13 11:54:43.561519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00a438c48bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pluspunkte', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gewichtung', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noten', schema=None) as batch_op:
        batch_op.drop_column('gewichtung')
        batch_op.drop_column('pluspunkte')

    # ### end Alembic commands ###
